### ISSUE TITLE
Add CI Integration for Jetworking Framework

### ISSUE THREAD

**Issue by JensK611** [JamitLabs/Jetworking#46]
To make sure that our framework is buildable at anytime we should integrate it into our CI.

**Comment by SimonNumberTwo** [comment]
CI added in the Jamit Labs Bitrise, see https://app.bitrise.io/build/5300b2b60f5302e9

It simply executes the tests whenever a PR is being posted or a merge to `develop` is done.

# ATTENTION:
The Webhook is not yet added as I am missing some access.

**Comment by JensK611** [comment]
CI and Webhooks has been added therefore we can close this issue.
