### ISSUE TITLE
Executor vs Executer as suffix

### ISSUE THREAD

**Issue by jjorn** [JamitLabs/Jetworking#51]
Both words are used in the current version. No one of them is wrong but this could make us be confused during implementation or debugging. I'd suggest to keep just one of them, not both.

**Comment by JensK611** [comment]
Yes you're totally right! I would prefer `executer`. It seems that `executor` has a more specific meaning:

```
"Executor" has a specific meaning. It's a legal term referring to the person who manages a deceased person's estate in accordance with that person's will. It's pronounced differently too, the emphasis is on the second syllable.
```
https://ell.stackexchange.com/questions/19860/executer-vs-executor
