### ISSUE TITLE
Encoder/Decoder Protocol

### ISSUE THREAD

**Issue by jamitJona** [JamitLabs/Jetworking#59]
Data received or provided to an endpoint is currently decoded/encoded via the `decoder` property (`encoder` respectively). These properties are of type JSONDecoder/JSONEncoder. We should introduce protocols which abstract the decode / encode function that are used in the `Client` class. This what we would be more flexible what kind of object we want to decode/encode. This way it would be possible to work with objects other then JSON (e.g. XML)

**Comment by jamitJona** [comment]
I created two branches on my fork to address this issue. 

The first branch adds options for the encoding/decoding to the configuration: [Click me](https://github.com/JamitLabs/Jetworking/compare/develop...jamitJona:feature/%2359-configuration-with-encoding-option  )

The second branch adds the same options to the endpoint: [Click me](https://github.com/JamitLabs/Jetworking/compare/develop...jamitJona:feature/%2359-endpoint-with-coding-options)

In personally like the second approach more since we can change the encoding/decoding for each endpoint. In comparison the first approach sets the encoding/decoding for the whole client.

Do you have opinions on which approach we should use? Also feedback to the implementation is appreciated.

**Comment by JensK611** [comment]
Resolved in #60
