### ISSUE TITLE
HTTPStatusCodeType issues

### ISSUE THREAD

**Issue by mrylmz** [JamitLabs/Jetworking#71]
The `HTTPStatusCodeType` should not contain type as postfix because it is clear that it is a type, also it seams that it is incomplete yet please provide all possible status codes or just replace the type with an `Int`.

**Comment by JensK611** [comment]
The `type` postfix in my mind is that it is categorized into `success`, `serverError`... maybe a more descriptive naming is `HTTPStatusCodeCategory` or could be dropped as you described.
