### ISSUE TITLE
What is an Executor?

### ISSUE THREAD

**Issue by mrylmz** [JamitLabs/Jetworking#72]
What is the exact purpose of an Executor and which other term could be used to make it more descriptive for users?

**Comment by JensK611** [comment]
The purpose of an `executer` is to execute the request in a specific way. For example the `SyncRequestExecuter` is executing the requests in a synchronous way. It is starting the next request after the previous one has been completed.

Is the naming descriptive enough or what's your suggestion?

**Comment by JensK611** [comment]
This has been resolved in #77
