### ISSUE TITLE
Spelling of „Executor“

### ISSUE THREAD

**Issue by knothed** [JamitLabs/Jetworking#88]
Throughout the code, „Executor“ is incorrectly spelled „Executer“. For example, [here](https://github.com/JamitLabs/Jetworking/tree/develop/Sources/Jetworking/Client/Executor/RequestExecuter), the files and folder names, and consequently the class names, are spelled incorrectly.

**Comment by mrylmz** [comment]
There are no references left which are using the spelling `Executor`. I think the `Executer` is the correct spelling to use here.

**Comment by knothed** [comment]
<img width="181" alt="image" src="https://user-images.githubusercontent.com/18039001/140514994-e8e6802a-3ac5-410d-b8c8-30e0f47291a2.png">

There are still directories called "Executor".

I think both spellings are correct for this use-case, but since all of the code uses "Executer", the directories should be adapted accordingly.
